name: Process release

on:
  release:
    types: [published]

jobs:
      build-container-image:
        runs-on: ubuntu-latest
        
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v2

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/benonions/taskd:latest
              docker push ghcr.io/benonions/taskd:latest

