replicaCount: 1

image:
  repository: ghcr.io/benonions/taskd
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 53589

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

